openapi: 3.0.1
info:
  title: Next Door
  description: 'Collection of Microservices'
  contact:
    email: ukbaranwal@gmail.com
  version: 1.0.0
servers:
- url: localhost:8080
- url: http://localhost:3000
tags:
- name: Vendor
  description: APIs for Vendors
- name: User
  description: APIs for Users
- name: Delivery Boys
  description: APIs for Delivery Boys

paths:
  /vendors/signup:
    post:
      tags:
      - Vendor
      summary: Signups a Vendor
      operationId: signupVendor
      requestBody:
        description: Vendor object that needs to be added
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Vendor'
        required: true
      responses:
        200:
          description: Vendor already Registered
        201:
          description: Signup was Successfull
        404:
          description: Not Found
        422:
          description: Validation Failed
        500:
          description: Server Error
          content: {}
  /vendors/signin:
    post:
      tags: 
        - Vendor
      summary: Logins a Vendor
      operationId: loginVendor
      requestBody:
        description: Email ID and Password of Vendor
        content:
          application/json:
            schema:
              required: 
                - email
                - password
              type: object
              properties: 
                email:
                  type: string
                  example: mystore@gmail.com
                password:
                  type: string
                  example: 123$%mystore
        required: true
      responses:
        202:
          description: Login was Successfull
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VendorResponse'
        204:
          description: Vendor not found
        401:
          description: Unauthorized Access
        404:
          description: Not Found
        422:
          description: Validation Failed
        500:
          description: Server Error
  /vendors/forgotpassword:
    post:
      tags: 
        - Vendor
      summary: Used to request reset pin to change password for vendors
      operationId: forgotPasswordRequest
      requestBody: 
        description: Email ID of Vendor
        content:
          application/json:
            schema: 
              required:
                - email
              type: object
              properties: 
                email:
                  type: string
                  example: mystore@gmail.com
        required: true
      responses:
        200:
          description: Reset Pin has been sent on Email 
        204:
          description: Vendor not found
        404:
          description: Not Found
        422:
          description: Validation Failed
        500:
          description: Server Error
    put:
      tags:
        - Vendor
      summary: Used to change password with the requested Pin
      operationId: forgotPasswordChange
      requestBody:
        description: Email ID along with Password and Secret Pin
        content:
          application/json:
            schema:
              required:
                - email
                - password
                - pin 
              type: object
              properties:
                email:
                  type: string
                  example: mystore@gmail.com
                password:
                  type: string
                  example: 123$%mystore
                pin: 
                  type: string
                  example: 1234
        required: true
      responses:
        202:
          description: Password has been changed
        204:
          description: Vendor not found
        404:
          description: Not Found
        422:
          description: Validation Failed
        500:
          description: Server Error
  /vendors/changepassword:
    post:
      tags: 
        - Vendor
      summary: Used to change password for vendors
      operationId: changePassword
      requestBody: 
        description: old and new password
        content:
          application/json:
            schema: 
              required:
                - password
                - new_password
              type: object
              properties: 
                password:
                  type: string
                  example: 12345j63
                new_password:
                  type: string
                  example: 123rf43re
        required: true
      responses:
        202:
          description: Password Successfully changed
        401:
          description: Unauthorized Access
        204:
          description: Vendor not found
        404:
          description: Not Found
        422:
          description: Validation Failed
        500:
          description: Server Error
  /vendors/updateStatus:
    put:
      tags: 
        - Vendor
      summary: Updates Shop status if it is open or closed
      operationId: updateStatus
      requestBody:
        description: boolean value shop_open
        content:
          application/json:
            schema:
              required: 
                - shop_open
              type: object
              properties: 
                shop_open:
                  type: boolean
                  example: false
        required: true
      responses:
        200:
          description: Successfully Updated
        401:
          description: Unauthorized Access
        404:
          description: Not Found
        422:
          description: Validation Failed
        500:
          description: Server Error
  /vendors/updateDashboard:
    put:
      tags: 
        - Vendor
      summary: Updates Dashboard
      operationId: updateDashboard
      requestBody:
        description: Used by vendors only first time
        content:
          application/json:
            schema:
              required: 
                - name
                - shop_name
                - address
                - city
                - tags
              type: object
              properties: 
                name:
                  type: string
                  example: Utkarsh
                shop_name:
                  type: string
                  example: UB Stores
                address:
                  type: string
                  example: B14/172
                city:
                  type: string
                  example: Kalyani
                tags:
                  type: string
                  example: Clothes, Shop
        required: true
      responses:
        200:
          description: Successfully Updated
        401:
          description: Unauthorized Access
        403:
          description: Forbidden Access
        404:
          description: Not Found
        422:
          description: Validation Failed
        500:
          description: Server Error
  /vendors/updateDashboardLogo:
    put:
      tags: 
        - Vendor
      summary: Updates Shop Logo
      operationId: updateDashboardLogo
      requestBody:
        description: Used by vendors to upload there logo
        content:
          multipart/form-data:
            schema:
              image:
                type: file
        required: true
      responses:
        200:
          description: Successfully Updated
        401:
          description: Unauthorized Access
        403:
          description: Forbidden Access
        404:
          description: Not Found
        422:
          description: Validation Failed
        500:
          description: Server Error    
  /vendors/deleteDashboardLogo:
    put:
      tags: 
        - Vendor
      summary: Deletes Shop Logo
      operationId: deleteDashboardLogo
      responses:
        200:
          description: Successfully Deleted
        401:
          description: Unauthorized Access
        403:
          description: Forbidden Access
        404:
          description: Not Found
        422:
          description: Validation Failed
        500:
          description: Server Error     
  /vendors/updateTime:
    put:
      tags: 
        - Vendor
      summary: Updates Shop Timing
      operationId: updateTime
      requestBody:
        description: Used by vendors to update there timings
        content:
          application/json:
            schema:
              required: 
                - opening_time
                - closing_time
              type: object
              properties: 
                opening_time:
                  type: string
                  example: 10AM
                closing_time:
                  type: string
                  example: 11PM
      required: true
      responses:
        200:
          description: Successfully Updated
        401:
          description: Unauthorized Access
        404:
          description: Not Found
        422:
          description: Validation Failed
        500:
          description: Server Error  
  /vendors/updateLocation:
    put:
      tags: 
        - Vendor
      summary: Updates Location
      operationId: updateLocation
      requestBody:
        description: Used by vendors to update their location
        content:
          application/json:
            schema:
              required: 
                - location_lat
                - location_long
              type: object
              properties: 
                location_lat:
                  type: string
                  example: 3.123245676564532
                location_long:
                  type: string
                  example: 4.2324565653425664
      required: true
      responses:
        200:
          description: Successfully Updated
        401:
          description: Unauthorized Access
        403:
          description: Forbidden Access
        404:
          description: Not Found
        422:
          description: Validation Failed
        500:
          description: Server Error    


components:
  schemas:
    Vendor:
      required:
      - name
      - email
      - phone
      - password
      - city
      - vendor_type
      type: object
      properties:
        name:
          type: string
          example: My Store
        email:
          type: string
          example: mystore@gmail.com
        city: 
          type: string
          example: Kalyani
        phone:
          type: string
          example: 1234567890
        password:
          type: string
          example: 123$%mystore
        vendor_type:
          type: integer
          example: 1
    VendorResponse:
      type: object
      properties:
        vendor_type:
          type: integer
          example: 1
        image_url: 
          type: string
          example: https://cdn.geekwire.com/wp-content/uploads/2020/02/amzngo1-630x420.jpeg
        name:
          type: string
          example: My Store
        email:
          type: string
          example: mystore@gmail.com
        phone:
          type: string
          example: 1234567890
        address: 
          type: string
          example: B-14/419
        password:
          type: string
          example: 123$%mystore
        opt_for_delivery_boy:
          type: boolean
          example: false
        local_store:
          type: boolean
          example: false
        owns_store: 
          type: boolean
          example: false
        tags:
          type: string
          example: grocery,food,shop
        shop_open:
          type: boolean
          example: true
        no_of_rating:
          type: integer
          example: 100
        rating:
          type: float
          example: 4.1
        verified:
          type: boolean
          example: true
        local_store:
          type: boolean
          example: false
        upi_id:
          type: string
          example: mystore@paytm
        paytm_no:
          type: string
          example: 1234567890
        location_lat:
          type: string
          example: "0.342455432"
        location_long:
          type: string
          example: "0.342455432"
        membership_active:
          type: boolean
          example: true
        payable: 
          type: float
          example: 1000.0
        owns_store: 
          type: boolean
          example: true
        opening_time: 
          type: string
          example: 11:00
        closing_time:
          type: string
          example: 8:00
        
